"""Walk-forward expected-return fusion using Ridge regression."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler

from .logistic_stack import logit_clip


@dataclass
class WalkForwardExpectedReturnFusion:
    """Map standardized CNN/RF logits into a predicted forward return.

    The resulting ``mu_hat`` is a cross-sectional ranking signal, not a
    calibrated probability. ``predict`` retrieves cached walk-forward
    forecasts generated by ``fit``; it does not infer arbitrary new dates.
    """

    alpha: float = 1.0
    label_lag_periods: int = 1
    start_year: Optional[int] = None
    end_year: Optional[int] = None
    min_train_rows: int = 1000
    eps: float = 1e-6

    def __post_init__(self) -> None:
        self.predictions_: Optional[pd.DataFrame] = None
        self.coefficients_: Optional[pd.DataFrame] = None

    def fit(self, df: pd.DataFrame) -> "WalkForwardExpectedReturnFusion":
        required = ["Date", "StockID", "p_cnn", "p_rf", "fwd_ret"]
        missing = [c for c in required if c not in df.columns]
        if missing:
            raise KeyError(f"missing required columns: {missing}")

        full = df.dropna(subset=["Date", "StockID", "p_cnn", "p_rf"]).copy()
        full["Date"] = pd.to_datetime(full["Date"], errors="coerce").dt.normalize()
        labeled = full.dropna(subset=["fwd_ret"]).copy()
        full["year"] = full["Date"].dt.year.astype(int)

        start = int(self.start_year if self.start_year is not None else full["year"].min())
        end = int(self.end_year if self.end_year is not None else full["year"].max())
        pred_parts = []
        coef_rows = []

        for target_year in range(start, end + 1):
            target = full[full["year"] == target_year].copy()
            if target.empty:
                continue

            first_target_date = target["Date"].min()
            prior_dates = np.array(sorted(labeled.loc[labeled["Date"] < first_target_date, "Date"].dropna().unique()))
            if len(prior_dates) <= int(self.label_lag_periods):
                continue

            max_train_date = pd.Timestamp(prior_dates[-(int(self.label_lag_periods) + 1)])
            train = labeled[labeled["Date"] <= max_train_date].copy()

            x_train_raw = np.column_stack([logit_clip(train["p_cnn"], self.eps), logit_clip(train["p_rf"], self.eps)])
            x_target_raw = np.column_stack([logit_clip(target["p_cnn"], self.eps), logit_clip(target["p_rf"], self.eps)])
            y_train = pd.to_numeric(train["fwd_ret"], errors="coerce").to_numpy(float)
            finite = np.isfinite(x_train_raw).all(axis=1) & np.isfinite(y_train)
            x_train_raw = x_train_raw[finite]
            y_train = y_train[finite]

            if len(y_train) < int(self.min_train_rows):
                continue

            scaler = StandardScaler()
            x_train = scaler.fit_transform(x_train_raw)
            x_target = scaler.transform(x_target_raw)

            model = Ridge(alpha=float(self.alpha), fit_intercept=True)
            model.fit(x_train, y_train)
            mu_hat = model.predict(x_target)
            target["mu_hat"] = mu_hat
            pred_parts.append(target[["Date", "StockID", "mu_hat"]])

            train_pred = model.predict(x_train)
            ss_res = float(np.sum((y_train - train_pred) ** 2))
            ss_tot = float(np.sum((y_train - y_train.mean()) ** 2))
            train_r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else np.nan
            coef_rows.append(
                {
                    "target_year": target_year,
                    "train_rows": len(y_train),
                    "max_train_date": max_train_date,
                    "intercept": float(model.intercept_),
                    "beta_std_logit_cnn": float(model.coef_[0]),
                    "beta_std_logit_rf": float(model.coef_[1]),
                    "train_r2": train_r2,
                }
            )

        if not pred_parts:
            raise ValueError("expected-return fusion produced no predictions")

        self.predictions_ = (
            pd.concat(pred_parts, ignore_index=True)
            .drop_duplicates(["Date", "StockID"], keep="last")
            .sort_values(["Date", "StockID"])
            .reset_index(drop=True)
        )
        self.coefficients_ = pd.DataFrame(coef_rows)
        return self

    def predict(self, df: pd.DataFrame) -> pd.Series:
        if self.predictions_ is None:
            raise ValueError("fit must be called before predict")
        keys = df[["Date", "StockID"]].copy()
        keys["Date"] = pd.to_datetime(keys["Date"], errors="coerce").dt.normalize()
        keys["StockID"] = keys["StockID"].astype(str)
        pred = self.predictions_.copy()
        pred["StockID"] = pred["StockID"].astype(str)
        merged = keys.merge(pred, on=["Date", "StockID"], how="left", sort=False)
        if merged["mu_hat"].isna().any():
            raise ValueError("predict received stock-date rows without cached walk-forward predictions")
        return pd.Series(merged["mu_hat"].to_numpy(float), index=df.index, name="up_prob")
