"""Leakage-aware annual walk-forward logistic stacking of expert forecasts."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

from .rank_blend import RankBlend


def logit_clip(values, eps: float = 1e-6) -> np.ndarray:
    p = np.clip(np.asarray(values, dtype=float), eps, 1.0 - eps)
    return np.log(p / (1.0 - p))


@dataclass
class WalkForwardLogisticStack:
    """Annual expanding-window logistic stack for CNN/RF probabilities.

    For target year ``y``, the scaler and logistic model are estimated only on
    nonmissing historical labels before the first target-year prediction date.
    ``label_lag_periods`` excludes the most recent labeled observation dates;
    callers must ensure this embargo covers their actual target horizon.
    ``predict`` retrieves cached walk-forward forecasts generated by ``fit``.
    """

    C: float = 1.0
    label_lag_periods: int = 1
    start_year: Optional[int] = None
    end_year: Optional[int] = None
    random_state: int = 1729
    warm_start_rank_blend: bool = True
    eps: float = 1e-6

    def __post_init__(self) -> None:
        self.predictions_: Optional[pd.DataFrame] = None
        self.coefficients_: Optional[pd.DataFrame] = None
        self.row_contributions_: Optional[pd.DataFrame] = None

    def fit(self, df: pd.DataFrame) -> "WalkForwardLogisticStack":
        required = ["Date", "StockID", "p_cnn", "p_rf", "y"]
        missing = [c for c in required if c not in df.columns]
        if missing:
            raise KeyError(f"missing required columns: {missing}")

        full = df.dropna(subset=["Date", "StockID", "p_cnn", "p_rf"]).copy()
        full["Date"] = pd.to_datetime(full["Date"], errors="coerce").dt.normalize()
        labeled = full.dropna(subset=["y"]).copy()
        full["year"] = full["Date"].dt.year.astype(int)
        labeled["year"] = labeled["Date"].dt.year.astype(int)

        start = int(self.start_year if self.start_year is not None else full["year"].min())
        end = int(self.end_year if self.end_year is not None else full["year"].max())

        rank_warm = RankBlend(0.5, 0.5)
        pred_parts = []
        coef_rows = []
        contrib_parts = []

        for target_year in range(start, end + 1):
            target = full[full["year"] == target_year].copy()
            if target.empty:
                continue

            first_target_date = target["Date"].min()
            prior_dates = np.array(sorted(labeled.loc[labeled["Date"] < first_target_date, "Date"].dropna().unique()))

            if len(prior_dates) <= int(self.label_lag_periods):
                if not self.warm_start_rank_blend:
                    continue
                target["up_prob"] = rank_warm.predict(target)
                pred_parts.append(target[["Date", "StockID", "up_prob"]])
                coef_rows.append(
                    {
                        "target_year": target_year,
                        "mode": "warm_start_rank_5050",
                        "train_rows": 0,
                        "max_train_date": pd.NaT,
                        "intercept": np.nan,
                        "beta_std_logit_cnn": np.nan,
                        "beta_std_logit_rf": np.nan,
                    }
                )
                continue

            max_train_date = pd.Timestamp(prior_dates[-(int(self.label_lag_periods) + 1)])
            train = labeled[labeled["Date"] <= max_train_date].copy()

            x_train_raw = np.column_stack([logit_clip(train["p_cnn"], self.eps), logit_clip(train["p_rf"], self.eps)])
            x_target_raw = np.column_stack([logit_clip(target["p_cnn"], self.eps), logit_clip(target["p_rf"], self.eps)])
            y_train = pd.to_numeric(train["y"], errors="coerce").to_numpy()
            finite = np.isfinite(x_train_raw).all(axis=1) & np.isfinite(y_train)
            x_train_raw = x_train_raw[finite]
            y_train = y_train[finite].astype(int)

            if len(np.unique(y_train)) < 2:
                raise ValueError(f"training labels have one class only for year {target_year}")

            scaler = StandardScaler()
            x_train = scaler.fit_transform(x_train_raw)
            x_target = scaler.transform(x_target_raw)

            model = LogisticRegression(
                C=float(self.C),
                solver="lbfgs",
                max_iter=500,
                random_state=int(self.random_state),
            )
            model.fit(x_train, y_train)

            beta_cnn = float(model.coef_[0, 0])
            beta_rf = float(model.coef_[0, 1])
            target["up_prob"] = model.predict_proba(x_target)[:, 1]
            pred_parts.append(target[["Date", "StockID", "up_prob"]])

            coef_rows.append(
                {
                    "target_year": target_year,
                    "mode": "walk_forward_logistic",
                    "train_rows": len(train),
                    "max_train_date": max_train_date,
                    "intercept": float(model.intercept_[0]),
                    "beta_std_logit_cnn": beta_cnn,
                    "beta_std_logit_rf": beta_rf,
                }
            )

            diag = target[["Date", "StockID"]].copy()
            diag["cnn_linear_contribution"] = beta_cnn * x_target[:, 0]
            diag["rf_linear_contribution"] = beta_rf * x_target[:, 1]
            contrib_parts.append(diag)

        if not pred_parts:
            raise ValueError("walk-forward logistic stack produced no predictions")

        self.predictions_ = (
            pd.concat(pred_parts, ignore_index=True)
            .drop_duplicates(["Date", "StockID"], keep="last")
            .sort_values(["Date", "StockID"])
            .reset_index(drop=True)
        )
        self.coefficients_ = pd.DataFrame(coef_rows)
        self.row_contributions_ = pd.concat(contrib_parts, ignore_index=True) if contrib_parts else pd.DataFrame()
        return self

    def predict(self, df: pd.DataFrame) -> pd.Series:
        if self.predictions_ is None:
            raise ValueError("fit must be called before predict")
        keys = df[["Date", "StockID"]].copy()
        keys["Date"] = pd.to_datetime(keys["Date"], errors="coerce").dt.normalize()
        keys["StockID"] = keys["StockID"].astype(str)
        pred = self.predictions_.copy()
        pred["StockID"] = pred["StockID"].astype(str)
        merged = keys.merge(pred, on=["Date", "StockID"], how="left", sort=False)
        if merged["up_prob"].isna().any():
            raise ValueError("predict received stock-date rows without cached walk-forward predictions")
        return pd.Series(merged["up_prob"].to_numpy(float), index=df.index, name="up_prob")
